name: CI UPDATE PERSONAL
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - uses: oleksiyrudenko/gha-git-credentials@v1
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
    - run: git checkout -b personal
    - run: git pull origin personal
    - run: git rebase master
    - run: git push origin personal -f
